trigger:
- master

variables:
  BUILD_COMMIT: 7081ebfb113b14abe64c8d0ef66d12e64f79f66b
  ANACONDA_ORG: ofajardo
  # set Anaconda token in azure

jobs:
  - template: azure/posix.yml
    parameters:
      name: macOS
      vmImage: macOS-13
      matrix:
        py_3.10_64:
          MB_PYTHON_VERSION: "3.10"
          MB_PYTHON_OSX_VER: "10.9"
        py_3.11_64:
          MB_PYTHON_VERSION: "3.11"
          MB_PYTHON_OSX_VER: "11"
        py_3.12_64:
          MB_PYTHON_VERSION: "3.12"
          MB_PYTHON_OSX_VER: "11"
        py_3.13_64:
          MB_PYTHON_VERSION: "3.13"
          MB_PYTHON_OSX_VER: "11"
        py_3.10_64_arm64:
          MB_PYTHON_VERSION: "3.10"
          MB_PYTHON_OSX_VER: "11"
          PLAT: arm64
          MACOSX_DEPLOYMENT_TARGET: "11.0"
        py_3.11_64_arm64:
          MB_PYTHON_VERSION: "3.11"
          MB_PYTHON_OSX_VER: "11"
          PLAT: arm64
          MACOSX_DEPLOYMENT_TARGET: "11.0"
        py_3.12_64_arm64:
          MB_PYTHON_VERSION: "3.12"
          MB_PYTHON_OSX_VER: "11"
          PLAT: arm64
          MACOSX_DEPLOYMENT_TARGET: "11.0"
        py_3.13_64_arm64:
          MB_PYTHON_VERSION: "3.13"
          MB_PYTHON_OSX_VER: "11"
          PLAT: arm64
          MACOSX_DEPLOYMENT_TARGET: "11.0"

  - template: azure/posix.yml
    parameters:
      name: linux
      vmImage: ubuntu-24.04
      matrix:
        py_3.10_64manylinux1:
          MB_PYTHON_VERSION: "3.10"
          MB_ML_VER: "2014"
        py_3.11_64manylinux1:
          MB_PYTHON_VERSION: "3.11"
          MB_ML_VER: "2014"
        py_3.12_64manylinux1:
          MB_PYTHON_VERSION: "3.12"
          MB_ML_VER: "2014"
        py_3.13_64manylinux1:
          MB_PYTHON_VERSION: "3.13"
          MB_ML_VER: "2014"

  - template: azure/posix.yml
    parameters:
      name: linuxaarch64
      vmImage: ubuntu-24.04
      matrix:
        py_3.10_aarch64manylinux2014:
          MB_PYTHON_VERSION: "3.10"
          MB_ML_VER: "2014"
          PLAT: "aarch64"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
        py_3.11_aarch64manylinux2014:
          MB_PYTHON_VERSION: "3.11"
          MB_ML_VER: "2014"
          PLAT: "aarch64"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
        py_3.12_aarch64manylinux2014:
          MB_PYTHON_VERSION: "3.12"
          MB_ML_VER: "2014"
          PLAT: "aarch64"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
        py_3.13_aarch64manylinux2014:
          MB_PYTHON_VERSION: "3.13"
          MB_ML_VER: "2014"
          PLAT: "aarch64"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
