trigger:
- master

variables:
  BUILD_COMMIT: 3009195d7bdfb310cd8e540d04704677bb317a6d
  ANACONDA_ORG: ofajardo
  # set Anaconda token in azure

jobs:
  - template: azure/posix.yml
    parameters:
      name: macOS
      vmImage: macOS-11
      matrix:
        py_3.8_64:
          MB_PYTHON_VERSION: "3.8"
          MB_PYTHON_OSX_VER: "10.9"
        py_3.9_64:
          MB_PYTHON_VERSION: "3.9"
          MB_PYTHON_OSX_VER: "10.9"
        py_3.10_64:
          MB_PYTHON_VERSION: "3.10"
          MB_PYTHON_OSX_VER: "10.9"
        py_3.11_64:
          MB_PYTHON_VERSION: "3.11"
          MB_PYTHON_OSX_VER: "11"
        py_3.12_64:
          MB_PYTHON_VERSION: "3.12"
          MB_PYTHON_OSX_VER: "11"
        py_3.8_64_arm64:
          MB_PYTHON_VERSION: "3.8"
          MB_PYTHON_OSX_VER: "10.9"
          PLAT: arm64
          MACOSX_DEPLOYMENT_TARGET: "11.0"
        py_3.9_64_arm64:
          MB_PYTHON_VERSION: "3.9"
          MB_PYTHON_OSX_VER: "10.9"
          PLAT: arm64
          MACOSX_DEPLOYMENT_TARGET: "11.0"
        py_3.10_64_arm64:
          MB_PYTHON_VERSION: "3.10"
          MB_PYTHON_OSX_VER: "11"
          PLAT: arm64
          MACOSX_DEPLOYMENT_TARGET: "11.0"
        py_3.11_64_arm64:
          MB_PYTHON_VERSION: "3.11"
          MB_PYTHON_OSX_VER: "11"
          PLAT: arm64
          MACOSX_DEPLOYMENT_TARGET: "11.0"
        py_3.12_64_arm64:
          MB_PYTHON_VERSION: "3.12"
          MB_PYTHON_OSX_VER: "11"
          PLAT: arm64
          MACOSX_DEPLOYMENT_TARGET: "11.0"

  - template: azure/posix.yml
    parameters:
      name: linux
      vmImage: ubuntu-20.04
      matrix:
        py_3.8_64manylinux1:
          MB_PYTHON_VERSION: "3.8"
          MB_ML_VER: "2014"
        py_3.9_64manylinux1:
          MB_PYTHON_VERSION: "3.9"
          MB_ML_VER: "2014"
        py_3.10_64manylinux1:
          MB_PYTHON_VERSION: "3.10"
          MB_ML_VER: "2014"
        py_3.11_64manylinux1:
          MB_PYTHON_VERSION: "3.11"
          MB_ML_VER: "2014"
        py_3.12_64manylinux1:
          MB_PYTHON_VERSION: "3.12"
          MB_ML_VER: "2014"

  - template: azure/posix.yml
    parameters:
      name: linuxaarch64
      vmImage: ubuntu-20.04
      matrix:
        py_3.8_aarch64manylinux2014:
          MB_PYTHON_VERSION: "3.8"
          MB_ML_VER: "2014"
          PLAT: "aarch64"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
        py_3.9_aarch64manylinux2014:
          MB_PYTHON_VERSION: "3.9"
          MB_ML_VER: "2014"
          PLAT: "aarch64"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
        py_3.10_aarch64manylinux2014:
          MB_PYTHON_VERSION: "3.10"
          MB_ML_VER: "2014"
          PLAT: "aarch64"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
        py_3.11_aarch64manylinux2014:
          MB_PYTHON_VERSION: "3.11"
          MB_ML_VER: "2014"
          PLAT: "aarch64"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
        py_3.12_aarch64manylinux2014:
          MB_PYTHON_VERSION: "3.12"
          MB_ML_VER: "2014"
          PLAT: "aarch64"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
